### ISSUE TITLE
Got a LevelDBError (Too many open files) when running a state sync

### ISSUE THREAD

**Issue by gsalgado** [ApeWorX/py-trie#39]
I saw this in the logs when running the StateDownloader on a fully synced ropsten DB (28 GB). We may be leaking file descriptors somewhere, or it may just be that we need to pass a higher `max_open_files` when creating a `LevelDB` database

```
Traceback (most recent call last):
  File "/home/salgado/src/py-evm/p2p/state.py", line 65, in handle_peer
    await self._handle_peer(peer)
  File "/home/salgado/src/py-evm/p2p/state.py", line 90, in _handle_peer
    self.scheduler.process([(node_key, node)])
  File "/home/salgado/virtualenvs/pyevm/lib/python3.6/site-packages/trie-1.3.1-py3.6.egg/trie/sync.py", line 168, in process
    self.commit(request)
  File "/home/salgado/virtualenvs/pyevm/lib/python3.6/site-packages/trie-1.3.1-py3.6.egg/trie/sync.py", line 184, in commit
    self.db[keccak(request.data)] = request.data
  File "/home/salgado/src/py-evm/evm/db/backends/base.py", line 40, in __setitem__
    return self.set(key, value)
  File "/home/salgado/src/py-evm/evm/db/backends/level.py", line 25, in set
    self.db.Put(key, value)
leveldb.LevelDBError: IO error: /home/salgado/.local/share/trinity/ropsten-full-3/1375440.ldb: Too many open files
```

**Comment by gsalgado** [comment]
geth doesn't seem to change the default for `max_open_files` so ideally we shouldn't have to either

**Comment by gsalgado** [comment]
Wrong repo
